name: Build and Release

on:
  push:
    paths:
      - 'src-tauri/tauri.conf.json'
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Setup Tauri Action
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: './' # specify the path to your project if it's not in the repository root

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev

      # - name: Install dependencies (macOS)
      #   if: matrix.platform == 'macos-latest'
      #   run: |
      #     # Specify macOS dependencies here

      # - name: Install dependencies (Windows)
      #   if: matrix.platform == 'windows-latest'
      #   run: |
      #     # Specify Windows dependencies here

      - name: Cache Rust dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build project
        run: yarn tauri build --target all
        env:
          RUST_BACKTRACE: full

      - name: List Artifacts
        run: ls -R src-tauri/target/release/bundle/

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/**/*.AppImage
            src-tauri/target/release/bundle/**/*.deb
            src-tauri/target/release/bundle/**/*.rpm
            src-tauri/target/release/bundle/**/*.exe
            src-tauri/target/release/bundle/**/*.msi
            src-tauri/target/release/bundle/**/*.dmg
            src-tauri/target/release/bundle/**/*.pkg
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
